apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: automatic-operator-approval
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - installplans
  verbs:
  - patch
  - get
  - list
  - watch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - subscriptions
  verbs:
  - get
  - list
  - watch
