---
openshift_pipelines_operator:
  namespace: openshift-pipelines-operator
  operatorGroup:
    spec:
  subscription:
    name: openshift-pipelines-operator-rh
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: openshift-pipelines-operator-rh
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: openshift-pipelines-operator-rh.v1.6.2

redhat_oadp_operator:
  namespace: redhat-oadp
  operatorGroup:
    spec:
      targetNamespaces:
      - openshift-adp
  subscription:
    name: redhat-oadp-operator
    spec:
      channel: stable-1.0
      installPlanApproval: Automatic
      name: redhat-oadp-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      startingCSV: oadp-operator.v1.0.2
...