---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.applcationNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/created-by: helm
spec:
  project: {{ .Values.project }}
  source:
    {{- toYaml .Values.source | nindent 4 }}
  destination:
    {{- toYaml .Values.destination | nindent 4 }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
...