apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
  storageClassName: {{ .Values.storageClassName }}