{{- range $key, $value := .Values }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: global-operators
  namespace: {{ $value.namespace }}
{{- if $value.operatorGroup.spec }}
spec:
  {{- toYaml $value.operatorGroup.spec | nindent 2 }}
{{- end}}
...
{{- end }}
