---
#openshift_example_app:
#  cascadeDelete: false
#  namespace: openshift-gitops
#  syncWave: 20
#  project: default
#  source:
#    repoURL: https://github.com/nccurry/openshift-helm-charts.git
#    path: application-charts/openshift-example-app
#    targetRevision: HEAD
#  destination:
#    namespace: openshift-example-app
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
#
#swiss_army_knife_image:
#  cascadeDelete: true
#  namespace: openshift-gitops
#  syncWave: 20
#  project: default
#  source:
#    repoURL: https://github.com/nccurry/openshift-helm-charts.git
#    path: application-charts/swiss-army-knife-image
#    targetRevision: HEAD
#  destination:
#    namespace: swiss-army-knife-image
#    server: https://kubernetes.default.svc
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
#    syncOptions:
#    - CreateNamespace=true
...