apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  defaultRoute: {{ .Values.defaultRoute }}
  managementState: {{ .Values.managementState }}
  {{- if .Values.nodeSelector }}
  nodeSelector:
    {{ toYaml .Values.nodeSelector }}
  {{- end }}
  replicas: {{ .Values.replicas | quote }}
  {{- if .Values.tolerations }}
  tolerations:
    {{- toYaml .Values.tolerations | trim | nindent 2 }}
  {{- end }}
  storage:
    pvc:
      claim: {{- if .Values.persistentVolumeClaim.deploy }}image-registry-storage{{- end }}