---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: appproject
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/created-by: helm
spec:
  clusterResourceBlacklist: []
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: The default AppProject for ArgoCD
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources: {}
  roles: []
  signatureKeys: []
  sourceRepos:
  - '*'
  syncWindows: []
...